# Generated by Django 6.0.6 on 2026-09-26 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='kind',
            field=models.CharField(choices=[('CASH', 'A cash account (checking, card, broker clearing account)'), ('DEPOT', 'A securities depot; its balance is the market valuation'), ('SAVINGS', 'A savings account (e.g. overnight money)')], default='CASH', help_text='Cash, securities depot, or savings.', max_length=10),
        ),
        migrations.AddField(
            model_name='bankconnection',
            name='link_mfa_session_id',
            field=models.CharField(blank=True, help_text='The pending second-factor challenge of a Scalable link.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bankconnection',
            name='link_next_poll_at',
            field=models.DateTimeField(blank=True, help_text='The device authorization is not polled again before this.', null=True),
        ),
        migrations.AddField(
            model_name='bankconnection',
            name='link_poll_interval',
            field=models.PositiveIntegerField(default=5, help_text='Seconds between polls of the device authorization, as the provider asks.'),
        ),
        migrations.AddField(
            model_name='bankconnection',
            name='link_step',
            field=models.CharField(blank=True, choices=[('DEVICE', 'Waiting for the user to approve the login code'), ('MFA', 'Waiting for the user to approve the login on their trusted device'), ('DONE', 'Logged in')], help_text='Where a Scalable link is in its login.', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='bankconnection',
            name='provider',
            field=models.CharField(choices=[('ENABLEBANKING', 'A PSD2 bank consent via Enable Banking'), ('SCALABLE', "A Scalable Capital broker login via Scalable's official CLI API")], default='ENABLEBANKING', help_text='Who the accounts are reached through.', max_length=20),
        ),
        migrations.AddField(
            model_name='bankconnection',
            name='provider_user_id',
            field=models.CharField(blank=True, help_text="The user's id at the provider (Scalable: the person id).", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bankconnection',
            name='secret',
            field=models.TextField(blank=True, help_text='Encrypted provider credentials (Scalable: DPoP key and tokens). Never exposed.', null=True),
        ),
        migrations.AddField(
            model_name='bankconnection',
            name='token_expires_at',
            field=models.DateTimeField(blank=True, help_text='When the stored access token runs out (Scalable).', null=True),
        ),
        migrations.AddField(
            model_name='bankconnection',
            name='token_lease_until',
            field=models.DateTimeField(blank=True, help_text='Held by a token refresh until then, so one replica rotates the refresh token at a time.', null=True),
        ),
        migrations.AddField(
            model_name='historicalbankconnection',
            name='link_step',
            field=models.CharField(blank=True, choices=[('DEVICE', 'Waiting for the user to approve the login code'), ('MFA', 'Waiting for the user to approve the login on their trusted device'), ('DONE', 'Logged in')], help_text='Where a Scalable link is in its login.', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalbankconnection',
            name='provider',
            field=models.CharField(choices=[('ENABLEBANKING', 'A PSD2 bank consent via Enable Banking'), ('SCALABLE', "A Scalable Capital broker login via Scalable's official CLI API")], default='ENABLEBANKING', help_text='Who the accounts are reached through.', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalbankconnection',
            name='provider_user_id',
            field=models.CharField(blank=True, help_text="The user's id at the provider (Scalable: the person id).", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='isin',
            field=models.CharField(blank=True, help_text='The security traded or paying out, if any.', max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='kind',
            field=models.CharField(blank=True, help_text="The provider's transaction type (Scalable: BUY, SELL, DEPOSIT, DISTRIBUTION, …); null for bank transactions.", max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Units of the security, if any.', max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='raw',
            field=models.JSONField(blank=True, default=dict, help_text='The transaction as the provider returned it.'),
        ),
        migrations.CreateModel(
            name='HoldingSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='The day the position refers to.')),
                ('isin', models.CharField(help_text="The security's ISIN.", max_length=12)),
                ('name', models.CharField(help_text="The security's name.", max_length=1000)),
                ('security_type', models.CharField(blank=True, help_text='ETF, STOCK, FUND, CRYPTO, …', max_length=40, null=True)),
                ('quantity', models.DecimalField(decimal_places=8, help_text='Units held (filled).', max_digits=24)),
                ('fifo_price', models.DecimalField(blank=True, decimal_places=8, help_text='Average buy-in price per unit (FIFO).', max_digits=24, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=8, help_text='The last quoted mid price per unit.', max_digits=24, null=True)),
                ('valuation', models.DecimalField(decimal_places=2, help_text="The position's market value.", max_digits=18)),
                ('currency', models.CharField(help_text='ISO currency of the valuation.', max_length=3)),
                ('raw', models.JSONField(blank=True, default=dict, help_text='The position as the provider returned it.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the snapshot was first taken.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the snapshot was last refreshed (a day can be synced several times).')),
                ('account', models.ForeignKey(help_text='The depot.', on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='finance.bankaccount')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('account', 'date', 'isin'), name='bank_hold_acct_date_isin')],
            },
        ),
    ]
