# Generated by Django 6.0.6 on 2026-09-26 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_scalable'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='bankaccount',
            name='bank_acct_next_sync',
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='last_error_code',
            field=models.CharField(blank=True, help_text='The machine-readable kind of ``last_error`` (a BankErrorCode).', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='rate_limited_until',
            field=models.DateTimeField(blank=True, help_text='The provider rate-limited this account; no sync is attempted before then.', null=True),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='sync_day',
            field=models.DateField(blank=True, help_text='The UTC day ``syncs_today`` refers to.', null=True),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='syncs_today',
            field=models.PositiveIntegerField(default=0, help_text="Syncs that reached the provider on ``sync_day`` (a provider's daily limit counts these)."),
        ),
        migrations.AddField(
            model_name='bankconnection',
            name='last_error_code',
            field=models.CharField(blank=True, help_text='The machine-readable kind of ``last_error`` (a BankErrorCode).', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='historicalbankconnection',
            name='last_error_code',
            field=models.CharField(blank=True, help_text='The machine-readable kind of ``last_error`` (a BankErrorCode).', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='kind',
            field=models.CharField(blank=True, choices=[('BUY', 'Security bought'), ('SELL', 'Security sold'), ('SAVINGS_PLAN', 'Savings-plan execution'), ('DEPOSIT', 'Cash paid in'), ('WITHDRAWAL', 'Cash paid out'), ('DISTRIBUTION', 'Dividend or fund distribution'), ('INTEREST', 'Interest'), ('FEE', 'Fee'), ('TAX', 'Tax'), ('TAX_RETURN', 'Tax refund'), ('TRANSFER_IN', 'Securities transferred in'), ('TRANSFER_OUT', 'Securities transferred out'), ('CASH_TRANSFER_IN', 'Cash transferred in'), ('CASH_TRANSFER_OUT', 'Cash transferred out'), ('SWAP_IN', 'Security swapped in'), ('SWAP_OUT', 'Security swapped out'), ('CURRENCY_SWITCH_BUY', 'Currency bought'), ('CURRENCY_SWITCH_SELL', 'Currency sold'), ('POCKET_MONEY', 'Pocket money'), ('REINVESTMENT', 'Reinvestment'), ('REINVESTMENT_DISTRIBUTION', 'Reinvested distribution'), ('REINVESTMENT_POCKET_MONEY', 'Reinvested pocket money'), ('CORPORATE_ACTION', 'Split, merger or other corporate action'), ('OTHER', 'A type this service does not know yet (see raw)')], help_text="The provider's transaction type (Scalable: BUY, SELL, DEPOSIT, DISTRIBUTION, …); null for bank transactions.", max_length=40, null=True),
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='next_sync_at',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='unattended_day',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='unattended_syncs',
        ),
    ]
