# Generated by Django 6.0.6 on 2026-09-26 09:20

import django.db.models.deletion
import pgvector.django.vector
from typing import Any

from django.db import migrations, models


def build_terms(apps: Any, schema_editor: Any) -> None:
    """Every category's terms (name + description phrases), embedded one by one."""
    from embeddings import engine
    from finance.textnorm import category_terms, term_text

    Category = apps.get_model("finance", "Category")
    CategoryTerm = apps.get_model("finance", "CategoryTerm")
    terms = [CategoryTerm(category_id=c.pk, text=text) for c in Category.objects.only("pk", "name", "description") for text in category_terms(c.name, c.description)]
    if engine.enabled() and terms:
        sources = [term_text(term.text) for term in terms]
        vectors = iter(engine.embed_texts([source for source in sources if source is not None]))
        for term, source in zip(terms, sources, strict=True):
            term.embedding = next(vectors) if source is not None else None
            term.embedding_model = engine.model_id()
    CategoryTerm.objects.bulk_create(terms, batch_size=500, ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_categories_semantic'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=256, editable=False, help_text='Unit-length embedding of name + description, by the model named in embedding_model; NULL when there is no text to embed', null=True)),
                ('embedding_model', models.CharField(blank=True, default='', editable=False, help_text='The embedding model that produced `embedding`. Rows whose value differs from the configured model are re-embedded in-process and are excluded from vector search until then', max_length=200)),
                ('text', models.CharField(help_text='The phrase, as written in the name or description.', max_length=300)),
                ('category', models.ForeignKey(help_text='The category.', on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='finance.category')),
            ],
            options={
                'indexes': [models.Index(fields=['embedding_model'], name='bank_term_emb_model_idx')],
                'constraints': [models.UniqueConstraint(fields=('category', 'text'), name='bank_term_cat_text')],
            },
        ),
            migrations.RunPython(build_terms, migrations.RunPython.noop),
    ]
