# Generated by Django 6.0.6 on 2026-09-26 09:51

import django.db.models.deletion
from django.db import migrations, models


SYNCER_FIELDS = ["raw", "last_synced_at", "sync_lease_until", "sync_day", "syncs_today", "rate_limited_until", "last_error", "last_error_code"]


def accounts_to_syncers(apps, schema_editor):
    """One syncer per existing account — connection or not — so no account loses its identity.

    Every existing transaction was synced, so it gets its account's syncer: the per-syncer
    incremental start (``fetch_since``) is then exactly what it was per account before.
    """
    BankAccount = apps.get_model("finance", "BankAccount")
    AccountSyncer = apps.get_model("finance", "AccountSyncer")
    Transaction = apps.get_model("finance", "Transaction")
    for account in BankAccount.objects.select_related("connection").iterator():
        syncer = AccountSyncer.objects.create(
            organization_id=account.organization_id,
            account=account,
            connection=account.connection,
            backend=account.connection.provider if account.connection else "ENABLEBANKING",
            remote_id=account.uid,
            identification_key=account.identification_key,
            **{name: getattr(account, name) for name in SYNCER_FIELDS},
        )
        Transaction.objects.filter(account=account).update(syncer=syncer, origin="SYNC")
        account.iban_normalized = (account.iban or "").replace(" ", "").upper() or None
        account.save(update_fields=["iban_normalized"])


def syncers_to_accounts(apps, schema_editor):
    """Back: the account takes its first syncer's fields (a second syncer is dropped)."""
    AccountSyncer = apps.get_model("finance", "AccountSyncer")
    BankAccount = apps.get_model("finance", "BankAccount")
    for account in BankAccount.objects.all().iterator():
        syncer = AccountSyncer.objects.filter(account=account).order_by("id").first()
        if syncer is None:
            account.uid = account.identification_key = f"account:{account.id}"
        else:
            account.connection_id = syncer.connection_id
            account.uid = syncer.remote_id
            account.identification_key = syncer.identification_key
            for name in SYNCER_FIELDS:
                setattr(account, name, getattr(syncer, name))
        account.save()


class Migration(migrations.Migration):

    dependencies = [
        ('authentikate', '0007_user_profile'),
        ('finance', '0005_category_terms'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountSyncer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backend', models.CharField(choices=[('ENABLEBANKING', 'A PSD2 bank consent via Enable Banking'), ('SCALABLE', "A Scalable Capital broker login via Scalable's official CLI API")], help_text='Which provider it pulls from.', max_length=20)),
                ('remote_id', models.CharField(help_text="The account's id at the provider within the current connection (EB: the session's account uid; Scalable: the portfolio or savings id).", max_length=200)),
                ('identification_key', models.CharField(help_text='Stable identity at the provider across connections.', max_length=500)),
                ('raw', models.JSONField(blank=True, default=dict, help_text='The account as the provider returned it.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the syncer was first linked.')),
                ('last_synced_at', models.DateTimeField(blank=True, help_text='When the last successful sync finished.', null=True)),
                ('sync_lease_until', models.DateTimeField(blank=True, help_text='Held by a running sync until then; a crashed sync frees it once passed.', null=True)),
                ('sync_day', models.DateField(blank=True, help_text='The UTC day ``syncs_today`` refers to.', null=True)),
                ('syncs_today', models.PositiveIntegerField(default=0, help_text="Syncs that reached the provider on ``sync_day`` (a provider's daily limit counts these).")),
                ('rate_limited_until', models.DateTimeField(blank=True, help_text='The provider rate-limited this syncer; no sync is attempted before then.', null=True)),
                ('last_error', models.TextField(blank=True, help_text='Why the last sync failed, if it did.', null=True)),
                ('last_error_code', models.CharField(blank=True, help_text='The machine-readable kind of ``last_error`` (a BankErrorCode).', max_length=30, null=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='bankaccount',
            name='bank_acct_org_ident_uniq',
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='iban_normalized',
            field=models.CharField(blank=True, help_text='The IBAN without spaces, upper-cased: what accounts are matched by.', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='import_key',
            field=models.CharField(blank=True, help_text='How an import identified an account that has no IBAN (``fg:<Referenzkonto>``).', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='origin',
            field=models.CharField(choices=[('SYNC', 'Pulled by a syncer from the provider'), ('IMPORT', 'Imported from a file; a sync that finds the same booking takes it over')], default='SYNC', help_text='Whether the bank fields were synced or imported.', max_length=10),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When the account was first seen.'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='iban',
            field=models.CharField(blank=True, help_text="The account's IBAN, if known.", max_length=64, null=True),
        ),
        migrations.AddIndex(
            model_name='bankaccount',
            index=models.Index(fields=['organization', 'iban_normalized'], name='bank_acct_org_iban'),
        ),
        migrations.AddConstraint(
            model_name='bankaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('import_key__isnull', False)), fields=('organization', 'import_key'), name='bank_acct_org_import_key'),
        ),
        migrations.AddField(
            model_name='accountsyncer',
            name='account',
            field=models.ForeignKey(help_text='The account it feeds.', on_delete=django.db.models.deletion.CASCADE, related_name='syncers', to='finance.bankaccount'),
        ),
        migrations.AddField(
            model_name='accountsyncer',
            name='connection',
            field=models.ForeignKey(blank=True, help_text='The consent or login it is currently reached through.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='syncers', to='finance.bankconnection'),
        ),
        migrations.AddField(
            model_name='accountsyncer',
            name='organization',
            field=models.ForeignKey(help_text='The organization this syncer belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='bank_syncers', to='authentikate.organization'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='syncer',
            field=models.ForeignKey(blank=True, help_text='The syncer that last wrote the bank fields (null for imported rows).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='finance.accountsyncer'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['syncer', 'booking_date'], name='bank_tx_syncer_date'),
        ),
        migrations.RunPython(accounts_to_syncers, syncers_to_accounts),
        migrations.RemoveField(
            model_name='bankaccount',
            name='connection',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='identification_key',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='last_error',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='last_error_code',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='last_synced_at',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='rate_limited_until',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='raw',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='sync_day',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='sync_lease_until',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='syncs_today',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='uid',
        ),
        migrations.AddConstraint(
            model_name='accountsyncer',
            constraint=models.UniqueConstraint(fields=('organization', 'backend', 'identification_key'), name='bank_sync_org_backend_ident'),
        ),
    ]
