# Generated by Django 6.0.6 on 2026-09-26 10:02

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentikate', '0007_user_profile'),
        ('datalayer', '0001_initial'),
        ('finance', '0006_account_syncers'),
        ('koherent', '0003_rename_assignation_to_task'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='import_raw',
            field=models.JSONField(blank=True, default=dict, help_text="What the import knew beyond the bank fields (the app's analysis: type, contract, tags, split parts). Survives a sync taking the row over."),
        ),
        migrations.AddField(
            model_name='transaction',
            name='import_ref',
            field=models.CharField(blank=True, help_text="The booking's id in the imported file (``fg:<Buchungs-ID>``): what makes re-importing the same file idempotent.", max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category_source',
            field=models.CharField(choices=[('NONE', 'Uncategorized'), ('RULE', 'Set by a rule'), ('MANUAL', 'Set by a user; rules never touch it'), ('SEMANTIC', 'Set because similar, already categorized transactions agreed; rules and users override it'), ('IMPORT', "Taken from an imported statement (through the import's category mapping); rules never touch it")], default='NONE', help_text='Who set the category; rules never override a manual one.', max_length=10),
        ),
        migrations.CreateModel(
            name='ImportCategoryMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('FINANZGURU', 'A Finanzguru transaction export (xlsx, or the same columns as CSV)')], default='FINANZGURU', help_text='The app whose categories this maps.', max_length=20)),
                ('main', models.CharField(help_text="The app's main category (Finanzguru: Analyse-Hauptkategorie).", max_length=200)),
                ('sub', models.CharField(blank=True, default='', help_text="The app's subcategory (Finanzguru: Analyse-Unterkategorie); empty if none.", max_length=200)),
                ('proposed', models.BooleanField(default=True, help_text='Still the automatic proposal; false once a user set it.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the pair was first seen.')),
                ('category', models.ForeignKey(blank=True, help_text='The category rows with this pair get; null leaves them to rules and suggestions.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_mappings', to='finance.category')),
                ('organization', models.ForeignKey(help_text='The organization this mapping belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='bank_import_mappings', to='authentikate.organization')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalImportCategoryMapping',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('source', models.CharField(choices=[('FINANZGURU', 'A Finanzguru transaction export (xlsx, or the same columns as CSV)')], default='FINANZGURU', help_text='The app whose categories this maps.', max_length=20)),
                ('main', models.CharField(help_text="The app's main category (Finanzguru: Analyse-Hauptkategorie).", max_length=200)),
                ('sub', models.CharField(blank=True, default='', help_text="The app's subcategory (Finanzguru: Analyse-Unterkategorie); empty if none.", max_length=200)),
                ('proposed', models.BooleanField(default=True, help_text='Still the automatic proposal; false once a user set it.')),
                ('created_at', models.DateTimeField(blank=True, editable=False, help_text='When the pair was first seen.')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('category', models.ForeignKey(blank=True, db_constraint=False, help_text='The category rows with this pair get; null leaves them to rules and suggestions.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='finance.category')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentikate.client')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, db_constraint=False, help_text='The organization this mapping belongs to.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='authentikate.organization')),
                ('task', models.ForeignKey(blank=True, help_text='The task during which the change occurred, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='koherent.task')),
                ('history_relation', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='provenance_entries', to='finance.importcategorymapping')),
            ],
            options={
                'verbose_name': 'historical import category mapping',
                'verbose_name_plural': 'historical import category mappings',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='StatementImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('FINANZGURU', 'A Finanzguru transaction export (xlsx, or the same columns as CSV)')], default='FINANZGURU', help_text='Which app or format the file came from.', max_length=20)),
                ('file_name', models.CharField(blank=True, help_text="The file's name as uploaded.", max_length=1000, null=True)),
                ('status', models.CharField(choices=[('PREVIEWED', 'Parsed and matched against the accounts; nothing written yet'), ('APPLIED', 'Written into the accounts'), ('FAILED', 'The file could not be read')], default='PREVIEWED', help_text='Previewed, applied, or failed.', max_length=20)),
                ('report', models.JSONField(blank=True, default=dict, help_text='What the import found and did: per source account its target and counts, unmapped categories, warnings.')),
                ('error', models.TextField(blank=True, help_text='Why the file could not be read, if it could not.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the file was previewed.')),
                ('applied_at', models.DateTimeField(blank=True, help_text='When the import was (last) applied.', null=True)),
                ('creator', models.ForeignKey(blank=True, help_text='The user who uploaded the file.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_imports', to=settings.AUTH_USER_MODEL)),
                ('file', models.ForeignKey(blank=True, help_text='The uploaded file (null for an import of a local file by the management command).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_imports', to='datalayer.bigfilestore')),
                ('organization', models.ForeignKey(help_text='The organization this import belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='bank_imports', to='authentikate.organization')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalStatementImport',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('source', models.CharField(choices=[('FINANZGURU', 'A Finanzguru transaction export (xlsx, or the same columns as CSV)')], default='FINANZGURU', help_text='Which app or format the file came from.', max_length=20)),
                ('file_name', models.CharField(blank=True, help_text="The file's name as uploaded.", max_length=1000, null=True)),
                ('status', models.CharField(choices=[('PREVIEWED', 'Parsed and matched against the accounts; nothing written yet'), ('APPLIED', 'Written into the accounts'), ('FAILED', 'The file could not be read')], default='PREVIEWED', help_text='Previewed, applied, or failed.', max_length=20)),
                ('report', models.JSONField(blank=True, default=dict, help_text='What the import found and did: per source account its target and counts, unmapped categories, warnings.')),
                ('error', models.TextField(blank=True, help_text='Why the file could not be read, if it could not.', null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False, help_text='When the file was previewed.')),
                ('applied_at', models.DateTimeField(blank=True, help_text='When the import was (last) applied.', null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentikate.client')),
                ('creator', models.ForeignKey(blank=True, db_constraint=False, help_text='The user who uploaded the file.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('file', models.ForeignKey(blank=True, db_constraint=False, help_text='The uploaded file (null for an import of a local file by the management command).', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='datalayer.bigfilestore')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, db_constraint=False, help_text='The organization this import belongs to.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='authentikate.organization')),
                ('task', models.ForeignKey(blank=True, help_text='The task during which the change occurred, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='koherent.task')),
                ('history_relation', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='provenance_entries', to='finance.statementimport')),
            ],
            options={
                'verbose_name': 'historical statement import',
                'verbose_name_plural': 'historical statement imports',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='transaction',
            name='statement_import',
            field=models.ForeignKey(blank=True, help_text='The import that last brought this booking in (kept when a sync takes the row over).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='finance.statementimport'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(condition=models.Q(('import_ref__isnull', False)), fields=('account', 'import_ref'), name='bank_tx_acct_import_ref'),
        ),
        migrations.AddConstraint(
            model_name='importcategorymapping',
            constraint=models.UniqueConstraint(fields=('organization', 'source', 'main', 'sub'), name='bank_impmap_org_src_pair'),
        ),
    ]
