"""Merchants, their aliases and locations (PostGIS), and the transaction fields that point at them."""

# Generated by Django 6.0.6 on 2026-09-26 10:03

import django.contrib.postgres.indexes
import django.db.models.deletion
import finance.geo
import pgvector.django.vector
import simple_history.models
from django.conf import settings
from django.contrib.postgres.operations import CreateExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentikate', '0007_user_profile'),
        ('finance', '0007_statement_imports'),
        ('koherent', '0003_rename_assignation_to_task'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    # PostGIS for MerchantLocation.point (a generated geography column, GiST-indexed). Not a
    # trusted extension, so this needs the superuser -- which the services connect as; a no-op
    # where daten's init script already created it. See finance.geo for why there is no GeoDjango.
    operations = [
        CreateExtension("postgis"),
        migrations.AddField(
            model_name='transaction',
            name='merchant_source',
            field=models.CharField(choices=[('NONE', 'No merchant'), ('AUTO', "Matched by one of the merchant's aliases; re-matched when aliases change"), ('MANUAL', 'Set by a user; matching never touches it')], default='NONE', help_text='How the merchant was set; matching never overrides MANUAL.', max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category_source',
            field=models.CharField(choices=[('NONE', 'Uncategorized'), ('RULE', 'Set by a rule'), ('MANUAL', 'Set by a user; rules never touch it'), ('SEMANTIC', 'Set because similar, already categorized transactions agreed; rules and users override it'), ('IMPORT', "Taken from an imported statement (through the import's category mapping); rules never touch it"), ('MERCHANT', "The merchant's default category; rules and users override it, it overrides semantic guesses")], default='NONE', help_text='Who set the category; rules never override a manual one.', max_length=10),
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=256, editable=False, help_text='Unit-length embedding of name + description, by the model named in embedding_model; NULL when there is no text to embed', null=True)),
                ('embedding_model', models.CharField(blank=True, default='', editable=False, help_text='The embedding model that produced `embedding`. Rows whose value differs from the configured model are re-embedded in-process and are excluded from vector search until then', max_length=200)),
                ('name', models.CharField(help_text="The merchant's display name.", max_length=300)),
                ('key', models.CharField(help_text='The normalized name; unique per organization.', max_length=300)),
                ('description', models.TextField(blank=True, default='', help_text='Notes about the merchant.')),
                ('website', models.URLField(blank=True, help_text="The merchant's website.", max_length=500, null=True)),
                ('logo_url', models.URLField(blank=True, help_text="An image URL for the merchant's logo.", max_length=1000, null=True)),
                ('online', models.BooleanField(default=False, help_text='Online only: no physical stores.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the merchant was created.')),
                ('category', models.ForeignKey(blank=True, help_text='The default category of its transactions (source MERCHANT).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merchants', to='finance.category')),
                ('organization', models.ForeignKey(help_text='The organization this merchant belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='bank_merchants', to='authentikate.organization')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalMerchant',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(help_text="The merchant's display name.", max_length=300)),
                ('key', models.CharField(help_text='The normalized name; unique per organization.', max_length=300)),
                ('description', models.TextField(blank=True, default='', help_text='Notes about the merchant.')),
                ('website', models.URLField(blank=True, help_text="The merchant's website.", max_length=500, null=True)),
                ('logo_url', models.URLField(blank=True, help_text="An image URL for the merchant's logo.", max_length=1000, null=True)),
                ('online', models.BooleanField(default=False, help_text='Online only: no physical stores.')),
                ('created_at', models.DateTimeField(blank=True, editable=False, help_text='When the merchant was created.')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('category', models.ForeignKey(blank=True, db_constraint=False, help_text='The default category of its transactions (source MERCHANT).', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='finance.category')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentikate.client')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, db_constraint=False, help_text='The organization this merchant belongs to.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='authentikate.organization')),
                ('task', models.ForeignKey(blank=True, help_text='The task during which the change occurred, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='koherent.task')),
                ('history_relation', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='provenance_entries', to='finance.merchant')),
            ],
            options={
                'verbose_name': 'historical merchant',
                'verbose_name_plural': 'historical merchants',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='transaction',
            name='merchant',
            field=models.ForeignKey(blank=True, help_text='Who the transaction was with.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='finance.merchant'),
        ),
        migrations.CreateModel(
            name='MerchantAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.CharField(help_text="Normalized words (lower-case, no numbers or boilerplate) a line's key must start with.", max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the alias was added.')),
                ('merchant', models.ForeignKey(help_text='The merchant it means.', on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='finance.merchant')),
                ('organization', models.ForeignKey(help_text='The organization.', on_delete=django.db.models.deletion.CASCADE, related_name='bank_merchant_aliases', to='authentikate.organization')),
            ],
        ),
        migrations.CreateModel(
            name='MerchantLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="A display name (e.g. 'Spar 3418', 'Spar Mariahilfer Straße').", max_length=300)),
                ('store_code', models.CharField(blank=True, help_text='The store number bank lines carry for this place; unique per merchant.', max_length=20, null=True)),
                ('street', models.CharField(blank=True, help_text='Street and number.', max_length=300, null=True)),
                ('postal_code', models.CharField(blank=True, help_text='Postal code.', max_length=20, null=True)),
                ('city', models.CharField(blank=True, help_text='City.', max_length=200, null=True)),
                ('region', models.CharField(blank=True, help_text='State or region.', max_length=200, null=True)),
                ('country', models.CharField(blank=True, help_text='ISO 3166-1 alpha-2 country code.', max_length=2, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='WGS84 latitude.', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='WGS84 longitude.', max_digits=9, null=True)),
                ('point', models.GeneratedField(db_persist=True, expression=finance.geo.MakePoint(models.F('longitude'), models.F('latitude')), help_text='The PostGIS point of latitude/longitude (NULL until both are known); what `near` queries use.', output_field=finance.geo.GeographyPointField())),
                ('source', models.CharField(choices=[('DISCOVERED', 'Created from a store number on a bank line; address unknown until filled in'), ('MANUAL', 'Entered by a user'), ('GEOCODED', 'Address and coordinates looked up with the geocoder')], default='MANUAL', help_text='Where the location came from.', max_length=12)),
                ('osm_id', models.CharField(blank=True, help_text='The OpenStreetMap object it was geocoded to (N123, W456).', max_length=40, null=True)),
                ('geocoded_at', models.DateTimeField(blank=True, help_text='When it was last geocoded.', null=True)),
                ('notes', models.TextField(blank=True, default='', help_text='Notes.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the location was created.')),
                ('merchant', models.ForeignKey(help_text='The merchant.', on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='finance.merchant')),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='merchant_location',
            field=models.ForeignKey(blank=True, help_text="Where: the merchant's store, when the line names one.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='finance.merchantlocation'),
        ),
        migrations.AddIndex(
            model_name='merchant',
            index=models.Index(fields=['embedding_model'], name='bank_merch_emb_model_idx'),
        ),
        migrations.AddConstraint(
            model_name='merchant',
            constraint=models.UniqueConstraint(fields=('organization', 'key'), name='bank_merch_org_key'),
        ),
        migrations.AddConstraint(
            model_name='merchantalias',
            constraint=models.UniqueConstraint(fields=('organization', 'pattern'), name='bank_malias_org_pattern'),
        ),
        migrations.AddIndex(
            model_name='merchantlocation',
            index=django.contrib.postgres.indexes.GistIndex(fields=['point'], name='bank_loc_point_gist'),
        ),
        migrations.AddConstraint(
            model_name='merchantlocation',
            constraint=models.UniqueConstraint(condition=models.Q(('store_code__isnull', False)), fields=('merchant', 'store_code'), name='bank_loc_merch_code'),
        ),
    ]
