# Generated by Django 6.0.6 on 2026-09-26 11:00

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentikate', '0007_user_profile'),
        ('finance', '0008_merchants'),
        ('koherent', '0003_rename_assignation_to_task'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='merchant_source',
            field=models.CharField(choices=[('NONE', 'No merchant'), ('AUTO', "Matched by one of the merchant's aliases; re-matched when aliases change"), ('RULE', 'Set by a merchant rule; re-matched when rules change'), ('MANUAL', 'Set by a user; matching never touches it')], default='NONE', help_text='How the merchant was set; matching never overrides MANUAL.', max_length=10),
        ),
        migrations.CreateModel(
            name='MerchantRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default=100, help_text='Lower runs first; the first matching rule wins.')),
                ('field', models.CharField(choices=[('COUNTERPARTY', 'Counterparty name'), ('REMITTANCE', 'Remittance information'), ('IBAN', 'Counterparty IBAN')], help_text='The transaction field the pattern is matched against.', max_length=20)),
                ('match', models.CharField(choices=[('CONTAINS', 'Contains'), ('EQUALS', 'Equals'), ('REGEX', 'Regular expression')], default='CONTAINS', help_text='How the pattern is compared (case-insensitive).', max_length=20)),
                ('pattern', models.CharField(help_text='The text or regular expression to match.', max_length=1000)),
                ('direction', models.CharField(choices=[('ANY', 'Money in and out'), ('OUT', 'Money out only'), ('IN', 'Money in only')], default='ANY', help_text='Only match money in, money out, or both.', max_length=10)),
                ('amount_min', models.DecimalField(blank=True, decimal_places=2, help_text='Only match when the absolute amount is at least this.', max_digits=18, null=True)),
                ('amount_max', models.DecimalField(blank=True, decimal_places=2, help_text='Only match when the absolute amount is at most this.', max_digits=18, null=True)),
                ('active', models.BooleanField(default=True, help_text='Inactive rules are skipped.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the rule was created.')),
                ('location', models.ForeignKey(blank=True, help_text='Pin this place (else a store number on the line decides).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rules', to='finance.merchantlocation')),
                ('merchant', models.ForeignKey(help_text='The merchant matching transactions get.', on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='finance.merchant')),
                ('organization', models.ForeignKey(help_text='The organization this rule belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='bank_merchant_rules', to='authentikate.organization')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalMerchantRule',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('priority', models.IntegerField(default=100, help_text='Lower runs first; the first matching rule wins.')),
                ('field', models.CharField(choices=[('COUNTERPARTY', 'Counterparty name'), ('REMITTANCE', 'Remittance information'), ('IBAN', 'Counterparty IBAN')], help_text='The transaction field the pattern is matched against.', max_length=20)),
                ('match', models.CharField(choices=[('CONTAINS', 'Contains'), ('EQUALS', 'Equals'), ('REGEX', 'Regular expression')], default='CONTAINS', help_text='How the pattern is compared (case-insensitive).', max_length=20)),
                ('pattern', models.CharField(help_text='The text or regular expression to match.', max_length=1000)),
                ('direction', models.CharField(choices=[('ANY', 'Money in and out'), ('OUT', 'Money out only'), ('IN', 'Money in only')], default='ANY', help_text='Only match money in, money out, or both.', max_length=10)),
                ('amount_min', models.DecimalField(blank=True, decimal_places=2, help_text='Only match when the absolute amount is at least this.', max_digits=18, null=True)),
                ('amount_max', models.DecimalField(blank=True, decimal_places=2, help_text='Only match when the absolute amount is at most this.', max_digits=18, null=True)),
                ('active', models.BooleanField(default=True, help_text='Inactive rules are skipped.')),
                ('created_at', models.DateTimeField(blank=True, editable=False, help_text='When the rule was created.')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentikate.client')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, db_constraint=False, help_text='Pin this place (else a store number on the line decides).', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='finance.merchantlocation')),
                ('merchant', models.ForeignKey(blank=True, db_constraint=False, help_text='The merchant matching transactions get.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='finance.merchant')),
                ('organization', models.ForeignKey(blank=True, db_constraint=False, help_text='The organization this rule belongs to.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='authentikate.organization')),
                ('task', models.ForeignKey(blank=True, help_text='The task during which the change occurred, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='koherent.task')),
                ('history_relation', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='provenance_entries', to='finance.merchantrule')),
            ],
            options={
                'verbose_name': 'historical merchant rule',
                'verbose_name_plural': 'historical merchant rules',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
