# Generated by Django 6.0.6 on 2026-09-26 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentikate', '0007_user_profile'),
        ('finance', '0009_merchant_rules'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('SCALABLE', "Scalable Capital's official API (the organization's own login)"), ('TWELVEDATA', 'Twelve Data (public REST API, API key)'), ('YAHOO', 'Yahoo Finance (unofficial public endpoints, no key; may break or rate-limit)')], help_text='Where the price came from.', max_length=12)),
                ('symbol', models.CharField(help_text="The source's symbol.", max_length=40)),
                ('date', models.DateField(help_text='The trading day.')),
                ('close', models.DecimalField(decimal_places=8, help_text="The day's closing (or last) price.", max_digits=24)),
                ('currency', models.CharField(help_text='ISO currency of the price.', max_length=3)),
                ('fetched_at', models.DateTimeField(auto_now=True, help_text='When it was last fetched.')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('source', 'symbol', 'date'), name='bank_price_src_sym_date')],
            },
        ),
        migrations.CreateModel(
            name='SecurityListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isin', models.CharField(help_text='The security.', max_length=12)),
                ('source', models.CharField(choices=[('SCALABLE', "Scalable Capital's official API (the organization's own login)"), ('TWELVEDATA', 'Twelve Data (public REST API, API key)'), ('YAHOO', 'Yahoo Finance (unofficial public endpoints, no key; may break or rate-limit)')], help_text='The price source this listing is for.', max_length=12)),
                ('symbol', models.CharField(help_text="The source's symbol (Scalable: the ISIN; Yahoo: VWCE.DE; Twelve Data: VWCE).", max_length=40)),
                ('exchange', models.CharField(blank=True, help_text='The exchange (Twelve Data: the MIC, e.g. XETR; else the OpenFIGI exchange code).', max_length=20, null=True)),
                ('name', models.CharField(blank=True, help_text="The security's name as the source knows it.", max_length=300, null=True)),
                ('currency', models.CharField(blank=True, help_text="The listing's trading currency, once a price was fetched.", max_length=3, null=True)),
                ('pinned', models.BooleanField(default=False, help_text='Chosen by a user: automatic resolution never changes it.')),
                ('resolved_at', models.DateTimeField(blank=True, help_text='When it was last resolved.', null=True)),
                ('fetched_at', models.DateTimeField(blank=True, help_text='When prices were last fetched for it.', null=True)),
                ('last_error', models.TextField(blank=True, help_text='Why the last fetch failed, if it did.', null=True)),
                ('organization', models.ForeignKey(help_text='The organization.', on_delete=django.db.models.deletion.CASCADE, related_name='bank_security_listings', to='authentikate.organization')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('organization', 'isin', 'source'), name='bank_listing_org_isin_src')],
            },
        ),
    ]
