# Generated by Django 6.0.6 on 2026-09-26 18:50

from typing import Any

from django.db import migrations, models


def fill_contexts(apps: Any, schema_editor: Any) -> None:
    """Rows that already have a merchant get its context and are left for re-embedding (reembed_stale)."""
    from finance.textnorm import context_words

    Transaction = apps.get_model("finance", "Transaction")
    for tx in Transaction.objects.filter(merchant__isnull=False).select_related("merchant__category", "merchant_location").iterator():
        m, place = tx.merchant, tx.merchant_location
        parts = [m.name, " ".join((m.description or "").split()[:12])]
        if m.category_id and not m.category.hidden:
            parts.append(m.category.name)
        if place is not None:
            parts += [place.name, place.city or ""]
        context = context_words(" ".join(p for p in parts if p)) or ""
        if context != tx.merchant_context:
            Transaction.objects.filter(pk=tx.pk).update(merchant_context=context, embedding_model="")


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_security_prices'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='merchant_context',
            field=models.TextField(blank=True, default='', help_text='What the merchant and place add to the embedding (name, short description, default category, place name, city); kept in step by finance.merchants.refresh_context.'),
        ),
            migrations.RunPython(fill_contexts, migrations.RunPython.noop),
    ]
