# Generated by Django 6.0.6 on 2026-10-10 09:53

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


def scalable_providers(apps, schema_editor):
    """Give every organization that already linked Scalable its Scalable provider, and attach its logins.

    A Scalable provider holds no credentials, so this needs only the database. Enable Banking
    consents cannot be attached here (the application's key is a file the database never saw):
    they attach to the organization's first Enable Banking provider when an admin creates it.
    """
    BankProvider = apps.get_model("finance", "BankProvider")
    BankConnection = apps.get_model("finance", "BankConnection")
    loose = BankConnection.objects.filter(provider="SCALABLE", bank_provider__isnull=True)
    for organization_id in sorted(set(loose.values_list("organization_id", flat=True))):
        provider = BankProvider.objects.filter(organization_id=organization_id, kind="SCALABLE").order_by("id").first()
        if provider is None:
            provider = BankProvider.objects.create(
                organization_id=organization_id,
                kind="SCALABLE",
                name="Scalable Capital",
                capabilities=["BALANCES", "HOLDINGS", "PRICES", "SCHEDULED_SYNC", "TRANSACTIONS"],
            )
        loose.filter(organization_id=organization_id).update(bank_provider=provider)


class Migration(migrations.Migration):

    dependencies = [
        ('authentikate', '0007_user_profile'),
        ('finance', '0011_merchant_context'),
        ('koherent', '0003_rename_assignation_to_task'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankconnection',
            name='provider',
            field=models.CharField(choices=[('ENABLEBANKING', 'A PSD2 bank consent via Enable Banking'), ('SCALABLE', "A Scalable Capital broker login via Scalable's official CLI API")], default='ENABLEBANKING', help_text='The kind of provider the accounts are reached through.', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalbankconnection',
            name='provider',
            field=models.CharField(choices=[('ENABLEBANKING', 'A PSD2 bank consent via Enable Banking'), ('SCALABLE', "A Scalable Capital broker login via Scalable's official CLI API")], default='ENABLEBANKING', help_text='The kind of provider the accounts are reached through.', max_length=20),
        ),
        migrations.CreateModel(
            name='BankProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('ENABLEBANKING', 'A PSD2 bank consent via Enable Banking'), ('SCALABLE', "A Scalable Capital broker login via Scalable's official CLI API")], help_text='Which provider this is an instance of.', max_length=20)),
                ('name', models.CharField(help_text='What the organization calls it.', max_length=200)),
                ('enabled', models.BooleanField(default=True, help_text='A disabled provider starts no links and syncs nothing; its consents can still be revoked.')),
                ('capabilities', models.JSONField(blank=True, default=list, help_text='The ProviderCapability values switched on, a subset of what the kind can do.')),
                ('settings', models.JSONField(blank=True, default=dict, help_text="The kind's non-secret settings (Enable Banking: application id, redirect URLs, consent days).")),
                ('secret', models.TextField(blank=True, help_text="Encrypted credentials of the kind (Enable Banking: the application's private key). Never exposed.", null=True)),
                ('daily_sync_limit', models.PositiveIntegerField(blank=True, help_text='Syncs per account per UTC day before the service stops asking the provider; null is unlimited.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the provider was set up.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When it was last changed.')),
                ('creator', models.ForeignKey(blank=True, help_text='The admin who set it up.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_providers', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='The organization this provider belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='bank_providers', to='authentikate.organization')),
            ],
        ),
        migrations.AddField(
            model_name='bankconnection',
            name='bank_provider',
            field=models.ForeignKey(blank=True, help_text="The organization's provider this consent was made through; null until it is attached to one.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connections', to='finance.bankprovider'),
        ),
        migrations.AddField(
            model_name='historicalbankconnection',
            name='bank_provider',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text="The organization's provider this consent was made through; null until it is attached to one.", null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='finance.bankprovider'),
        ),
        migrations.CreateModel(
            name='HistoricalBankProvider',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('kind', models.CharField(choices=[('ENABLEBANKING', 'A PSD2 bank consent via Enable Banking'), ('SCALABLE', "A Scalable Capital broker login via Scalable's official CLI API")], help_text='Which provider this is an instance of.', max_length=20)),
                ('name', models.CharField(help_text='What the organization calls it.', max_length=200)),
                ('enabled', models.BooleanField(default=True, help_text='A disabled provider starts no links and syncs nothing; its consents can still be revoked.')),
                ('capabilities', models.JSONField(blank=True, default=list, help_text='The ProviderCapability values switched on, a subset of what the kind can do.')),
                ('settings', models.JSONField(blank=True, default=dict, help_text="The kind's non-secret settings (Enable Banking: application id, redirect URLs, consent days).")),
                ('daily_sync_limit', models.PositiveIntegerField(blank=True, help_text='Syncs per account per UTC day before the service stops asking the provider; null is unlimited.', null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False, help_text='When the provider was set up.')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, help_text='When it was last changed.')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentikate.client')),
                ('creator', models.ForeignKey(blank=True, db_constraint=False, help_text='The admin who set it up.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_relation', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='provenance_entries', to='finance.bankprovider')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, db_constraint=False, help_text='The organization this provider belongs to.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='authentikate.organization')),
                ('task', models.ForeignKey(blank=True, help_text='The task during which the change occurred, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='koherent.task')),
            ],
            options={
                'verbose_name': 'historical bank provider',
                'verbose_name_plural': 'historical bank providers',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddConstraint(
            model_name='bankprovider',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='bank_provider_org_name'),
        ),
        migrations.RunPython(scalable_providers, migrations.RunPython.noop),
    ]
