# Generated by Django 6.0.6 on 2026-10-10 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_bank_providers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankconnection',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Waiting for the user to approve at the bank'), ('ACTIVE', 'Consent granted; accounts can be synced'), ('EXPIRED', 'Consent ran out or was withdrawn at the bank; relink to continue'), ('REVOKED', 'Revoked by a user of this service'), ('FAILED', 'The link was never completed'), ('CANCELLED', 'The user dropped the login before it was finished')], default='PENDING', help_text='Where this consent is in its lifecycle.', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalbankconnection',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Waiting for the user to approve at the bank'), ('ACTIVE', 'Consent granted; accounts can be synced'), ('EXPIRED', 'Consent ran out or was withdrawn at the bank; relink to continue'), ('REVOKED', 'Revoked by a user of this service'), ('FAILED', 'The link was never completed'), ('CANCELLED', 'The user dropped the login before it was finished')], default='PENDING', help_text='Where this consent is in its lifecycle.', max_length=20),
        ),
    ]
